### ISSUE TITLE
Add the ability to verify certs via DANE

### ISSUE THREAD

**Issue by vbrown608** [EFForg/starttls-backend#103]
Related to EFForg/starttls-everywhere#72 we should add the ability to verify certs via DANE, as well as via CA-based root programs.

Migrated from starttls-check, opened by @jgillula on 7/13

**Comment by sydneyli** [comment]
I don't think we should do this. We should limit the scope of the website to reflect its primary purpose, which is to onboard people onto some downgrade-prevention mechanism in the absence of DNSSEC.

We could potentially link to another DANE checking tool from our website rather than re-inventing the wheel.

I've opened EFForg/starttls-frontend#221 to track this messaging.
