### ISSUE TITLE
More detailed ciphersuite report

### ISSUE THREAD

**Issue by vbrown608** [EFForg/starttls-backend#97]
Migrated from starttls-check, opened by @sydneyli on 6/7

**Comment by sydneyli** [comment]
I don't think we should do this. We should limit the scope of the website to reflect its primary purpose, which is to onboard people onto some STARTTLS downgrade-prevention mechanism.

In the results, we could potentially link to another comprehensive TLS-checking tool from our website rather than re-inventing the wheel.

I've opened  EFForg/starttls-frontend#221 to track the progress on the "re-scoping" thing.
